spring.application.name=spms-backend
spring.jpa.hibernate.ddl-auto=update
spring.datasource.dbcp2.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://database-fsad.cotysoa4knc7.us-east-1.rds.amazonaws.com/sdp
spring.datasource.username=admin
spring.datasource.password=NikithaM
spring.jpa.show-sql=true
app.jwt.secret=spmsBasicJwtSecretKeyForKluProject2026Spms
app.jwt.expiration-ms=86400000
